CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT,
  password_hash TEXT NOT NULL,
  role_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('pre_validated', 'blocked', 'committed', 'rolled_back', 'error')),
  source_file TEXT NOT NULL,
  source_hash TEXT NOT NULL,
  operation_file_path TEXT NOT NULL,
  company_file_path TEXT NOT NULL,
  records_atestados INTEGER NOT NULL DEFAULT 0,
  records_funcionarios INTEGER NOT NULL DEFAULT 0,
  records_afastados INTEGER NOT NULL DEFAULT 0,
  total_dias INTEGER NOT NULL DEFAULT 0,
  total_atestados INTEGER NOT NULL DEFAULT 0,
  validation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_json JSONB,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  prevalidated_at TIMESTAMPTZ,
  committed_at TIMESTAMPTZ,
  rolled_back_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS imported_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  file_role TEXT NOT NULL CHECK (file_role IN ('operation', 'company')),
  original_name TEXT NOT NULL,
  stored_path TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapa TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  funcao TEXT NOT NULL,
  origem_preferencial TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  crm TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (nome, crm)
);

CREATE TABLE IF NOT EXISTS cid_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capitulo TEXT NOT NULL,
  subcategoria TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (capitulo, subcategoria)
);

CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
  cid_id BIGINT REFERENCES cid_codes(id) ON DELETE SET NULL,
  origem TEXT NOT NULL,
  source_sheet TEXT NOT NULL,
  excel_row INTEGER NOT NULL,
  data_recebimento DATE,
  periodo TEXT NOT NULL,
  data_inicial DATE,
  data_final DATE,
  total_no_mes INTEGER NOT NULL,
  tipo_duracao TEXT NOT NULL,
  ano INTEGER,
  mes TEXT NOT NULL,
  atestados INTEGER NOT NULL,
  afastamento_inss TEXT NOT NULL DEFAULT '',
  observacao_gestores TEXT NOT NULL DEFAULT '',
  tratativa_seguranca TEXT NOT NULL DEFAULT '',
  tratativa_diretoria TEXT NOT NULL DEFAULT '',
  tratativa_jonilton TEXT NOT NULL DEFAULT '',
  raw_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS absences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
  cid_id BIGINT REFERENCES cid_codes(id) ON DELETE SET NULL,
  origem TEXT NOT NULL,
  source_sheet TEXT NOT NULL,
  excel_row INTEGER NOT NULL,
  colaborador TEXT NOT NULL,
  periodo TEXT NOT NULL,
  total INTEGER NOT NULL,
  ano INTEGER,
  mes TEXT NOT NULL,
  raw_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_validations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
  scope TEXT NOT NULL,
  status TEXT NOT NULL,
  validation_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT REFERENCES import_batches(id) ON DELETE CASCADE,
  severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
  scope TEXT NOT NULL,
  row_ref TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL DEFAULT '',
  ip_address INET,
  user_agent TEXT NOT NULL DEFAULT '',
  details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_certificates_batch ON certificates(batch_id);
CREATE INDEX IF NOT EXISTS idx_certificates_employee ON certificates(employee_id);
CREATE INDEX IF NOT EXISTS idx_certificates_dates ON certificates(data_inicial, data_final);
CREATE INDEX IF NOT EXISTS idx_absences_batch ON absences(batch_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_batches_status_version ON import_batches(status, version DESC);
